server:
  port: 9090


  spring:
    servlet:
      multipart:
        max-file-size: 300MB
        max-request-size: 100MB

  datasourse:
    url: jdbc:mysql://127.0.0.1:3306/db_soft1921?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: Gin20001217
    driver-class-name: com.mysql.cj.jdbc.Driver
